export const FILTERS_CATEGORY = {
  all: "all",
  smartphones: "smartphones",
  laptops: "laptops",
  fragrances: "fragrances",
  skincare: "skincare",
  groceries: "groceries",
  home: "home-decoration",
  furniture: "furniture",
  tops: "tops",
  womens: "womens-dresses",
  womens: "womens-shoes",
  mens: "mens-shirts",
  mens: "mens-shoes",
  mens: "mens-watches",
  womens: "womens-watches",
  womens: "womens-bags",
  womens: "womens-jewellery",
  sunglasses: "sunglasses",
  automotive: "automotive",
  motorcycle: "motorcycle",
  lighting: "lighting",
};
